feat: Set Windows Driver Type as Standard
lord-carlos/nvidia-update pull request #26
Opened 2019-10-27 13:10 UTC by link-webcreations

There is a new option in the NVIDIA driver searcher named as Windows Driver Type. (https://www.nvidia.com/Download/Find.aspx?lang=en-us#)

"Standard" packages are those that do not require the DCH driver components.
"DCH" (Declarative, Componentized, Hardware Support Apps) refers to new packages preinstalled by OEMS implementing the Microsoft Universal Driver paradigm.
DCH drivers cannot be installed over a standard system, and Standard drivers cannot be installed over a DCH system.

dtcid=0 mean Standard
dtcid=1 means DCH

2019-10-27 13:31 UTC, link-webcreations commented
In order to improve this change, we should check what's currently installed (Standard/DCH) during the # Checking currently installed driver version session:
https://github.com/lord-carlos/nvidia-update/blob/master/nvidia.ps1#L50

And then set the "dtcid" value accordingly.

2019-10-27 13:42 UTC, link-webcreations commented
Also, the package name will change. Ex:

440.97-desktop-win10-64bit-international-dch-whql.exe
vs
440.97-desktop-win10-64bit-international-whql.exe

2019-10-28 20:37 UTC, lord-carlos requested changes
Thank for the PR.
Just two minor text changes if you have the time for it.

2019-10-28 20:37 UTC, lord-carlos commented on README.md
> +Q. How is checked the latest driver version from Nvidia website ?
This sounds wrong? "How is checked"? Maybe "How do we check for the .."?

2019-10-28 20:37 UTC, lord-carlos commented on nvidia.ps1
> +    Write-Host "DCH driver are not yet supported."
Maybe add some more information. Maybe just a single line that windows will keep DCH driver up to date? Or just a link?

2019-10-30 19:47 UTC, link-webcreations commented
Hello @lord-carlos,
I have update the PR, please let me know if the changes suit you :)

2019-10-30 20:59 UTC, merged